# FEEDS
public_feeds_dataset: public_data_feeds_type_1
public_feeds_finance_dataset: public_data_feeds_type_1_finance
sample_feeds_dataset: public_data_feeds_sample
sample_bucket: pby-public-data-feed-sample
store_visits_table: store_visits
store_visits_trend_table: store_visits_trend
store_visitors_table: store_visitors
placekeys_table: placekeys
store_visits_daily_table: store_visits_daily

# FEED DAGS
placekeys_feed: products-feeds-accuracy-placekeys