raw_visits_table: sample_visits
poi_visits_scaled_dataset: poi_visits_scaled
device_clusters_dataset: device_clusters
visitors_homes_table: visitors_homes
device_homes_dataset: device_homes
demographics_site_procedure: storage-prod-olvin-com.demographics.site_analysis
visitors_demographics_table: visitors_demographics
zipcodes_dataset: device_zipcodes
visitors_zip4_table: visitors_zip4
area_geometries_dataset: area_geometries
zipcodes_table: zipcodes
state_demographics_table: state_demographics
places_dataset: sg_places
places_table: 20211101
site_selection_bucket: site-selection-files-prod-olvin-com
trade_area_table: trade_area
trade_cells_table: trade_cells
trade_zipcodes_table: trade_zipcodes
trade_cblocks_table: trade_cblocks
cblocks_table: census_blocks

poi_visits_dataset: poi_visits
ground_truth_volume_dataset: ground_truth_volume_model
ground_truth_volume_table: met_area_poi_monthly_visits

raw_visits_one_mile_table: sample_visits_1_mile_buffer
brands_table: brands

chain_ranking_state_table: chain_ranking_state
chain_ranking_local_table: chain_ranking_local
chain_ranking_national_table: chain_ranking_national
visits_per_sq_ft_state_table: visits_per_sq_ft_state
visits_per_sq_ft_local_table: visits_per_sq_ft_local
visits_per_sq_ft_national_table: visits_per_sq_ft_national

psychographics_brand_table: psychographics_brand
psychographics_category_table: psychographics_category
void_brand_table: void_brand
void_category_table: void_category

monthly_visits_table: monthly_visits
visits_estimation_dataset: sg_visits_estimation_output
visits_estimation_table: poi_daily

coordinates_table: coordinates
median_table: median_table

pipeline_label_value: site_analysis