# POSTGRES DATASET
postgres_batch_dataset: postgres_batch
sgplaceraw_table: SGPlaceRaw
sgplaceactivity_table: SGPlaceActivity
sgbrandraw_table: SGBrandRaw
sgplacedailyvisitsraw_table: SGPlaceDailyVisitsRaw
sgplacemonthlyvisitsraw_table: SGPlaceMonthlyVisitsRaw
hourly_table: SGPlaceHourlyAllVisitsRaw
Version_table: Version
backfill_start_date: '2019-01-01'
dag-products-postgres: products-postgres

# PUBLIC FEEDS DATASET
public_feeds_dataset: public_data_feeds_type_1
public_feeds_finance_dataset: public_data_feeds_type_1_finance
public_feeds_staging_dataset: public_data_feeds_type_1_staging
store_visits_table: store_visits
store_visits_temp_table: store_visits_temp
store_visits_snapshot_table: store_visits_snapshot_table
store_visits_daily_snapshot_table: store_visits_daily_snapshot
store_visits_daily_table: store_visits_daily

# PLACES DATASET
places_dataset: sg_places
places_dynamic_table: places_dynamic

# BASE TABLES DATASET
base_tables_dataset: sg_base_tables
non_sensitive_naics_codes_table: non_sensitive_naics_codes

# GCS BUCKET
raw_feed_bucket: pby-public-data-feed-type-1
raw_feed_finance_bucket: pby-public-data-feed-type-1-finance
dataproc_region: europe-west1
versioning_bucket: pby-product-p-gcs-euwe1-data_feeds_base_table_versions