sns-raw-dataset: sns_raw
sns-raw-traffic-formatted-table: raw_traffic_formatted

accessible-by-olvin-dataset: accessible_by_olvin
accessible-by-olvin-almanac-dataset: accessible_by_olvin_almanac
visits-estimation-metrics-dataset: visits_estimation_metrics
logging-rt-groups-gt-scaled-table: logging_rt_groups_gt_scaled
logging-rt-factors-tier-id-missing-table: logging_rt_factors_tier_id_missing
logging-rt-factors-tier-id-factors-distribution-table: logging_rt_factors_tier_id_factors_distribution
logging-rt-supervised-output-factors-distribution-table: logging_rt_supervised_output_factors_distribution
logging-rt-supervised-output-pois-unchanged-table: logging_rt_supervised_output_pois_unchanged
logging-rt-supervised-visits-table: logging_rt_supervised_visits
logging-rt-factors-final_brand_adjustment-table: logging_rt_factors_final_brand_adjustment
logging-rt-factors-final_brand_adjustment-distribution-table: logging_rt_factors_final_brand_adjustment_distribution
sensors_monitoring_business_table: sensors_monitoring_business
sensors_monitoring_location_table: sensors_monitoring_location
sensors_monitoring_business_metrics_table: sensors_monitoring_business_metrics
sensors_monitoring_location_metrics_table: sensors_monitoring_location_metrics
monitoring-supervised-inference-dag-table: monitoring_supervised_inference_dag

postgres-batch-dataset: postgres_batch
postgres-rt-dataset: postgres_rt
postgres-mv-rt-dataset: postgres_mv_rt
sgplacedailyvisitsraw-table: SGPlaceDailyVisitsRaw
sgplacemonthlyvisitsraw-table: SGPlaceMonthlyVisitsRaw
sgplaceranking-table: SGPlaceRanking
sgplaceraw-table: SGPlaceRaw
sgplaceactivity-table: SGPlaceActivity
sgbrandraw-table: SGBrandRaw
sgbranddailyvisits-table: SGBrandDailyVisits
sgbrandmonthlyvisits-table: SGBrandMonthlyVisits
sgbrandstatedailyvisits-table: SGBrandStateDailyVisits
sgbrandstatemonthlyvisits-table: SGBrandStateMonthlyVisits
version-table: Version

area-geometries-dataset: area_geometries
geo-us-boundaries-cbsa-table: geo_us_boundaries-cbsa

visits-estimation-supervised-dataset: visits_estimation_ground_truth_supervised
list-sns-pois-table: list_sns_pois
class-pois-sns-business-table: class_pois_sns_business
class-pois-sns-location-table: class_pois_sns_location
adjustments-events-usage-table: adjustments_events_usage
rt-gt-scaled-groups-business-table: rt_group_business_gt_scaled
rt-groups-business-class-1-table: rt_group_business_class_1_pois
batch-gt-scaled-groups-business-table: batch_group_business_gt_scaled
rt-gt-scaled-groups-location-table: rt_group_location_gt_scaled
batch-gt-scaled-groups-location-table: batch_group_location_gt_scaled
group-business-gt-scaled-prediction-table: group_business_gt_scaled_prediction
group-location-gt-scaled-prediction-table: group_location_gt_scaled_prediction
rt-factors-tier-id-business-table: rt_factors_tier_id_business
rt-factors-tier-id-location-table: rt_factors_tier_id_location
rt-supervised-input-processed-table: rt_supervised_input_processed
batch-supervised-input-processed-table: batch_supervised_input_processed
rt-supervised-output-table: rt_supervised_output
batch-supervised-output-table: batch_supervised_output
rt-output-factor-table: rt_output_factor
rt-visits-estimation-algo-output-table: rt_visits_estimation_algo_output
rt-visits-estimation-table: rt_visits_estimation

accessible-by-sns-dataset: accessible_by_sns
daily-feed-runs-table: daily_feed_runs
yoy-dates-nrf-calendar-table: yoy_dates_nrf_calendar

model-bucket: sns-process-p-gcs-euwe1-models
model-prefix: supervised-visits-estimation
postgres-staging-bucket: postgres-database-tables-staging
postgres-daily-bucket: pby-product-p-gcs-euwe1-pgdaily
postgres-dev-conn-id: postgres_gcp_dev
postgres-staging-conn-id: postgres_gcp_staging
pg-send-vm-zone: us-east4-b
postgres_db_raw_tables:
  - SGPlaceRanking
  - Version

postgres_db_mv_tables:
  - SGPlaceDailyVisitsRaw
  - SGPlaceMonthlyVisitsRaw
  - SGBrandDailyVisits
  - SGBrandMonthlyVisits
  - SGBrandStateDailyVisits
  - SGBrandStateMonthlyVisits

postgres_db_tables_in_bq:
  - SGPlaceDailyVisitsRaw

uniqueness_check_input_tables_list:
  - SGPlaceDailyVisitsRaw
  - SGPlaceMonthlyVisitsRaw
  - SGPlaceRanking