compute_project: compute-prod-olvin-com
storage_project: storage-dev-olvin-com
storage_prod: storage-prod-olvin-com
project: storage-prod-olvin-com
sns_project: sns-vendor-olvin-poc


inference_app: https://inference-pubsub-app-g6qya4cuaq-ew.a.run.app
#https://inference-app-g6qya4cuaq-ew.a.run.app
pub_sub_topic: inference-topic
pub_sub_topic_pull: inference-topic-pull-subs

inference_input_pip_req: >-
  pyspark==3.0.1

dataproc_region: europe-west1
visits_estimation_bucket: pby-process-p-gcs-euwe1-visits_estimation
py_main_file: yearly-seasonality/dist/main.py
py_dist: yearly-seasonality/dist/jobs.zip
yearly_seasonality_adjustment_input_table: yearly_seasonality_adjustment_input
yearly_seasonality_adjustment_brand_ratios_table: yearly_seasonality_adjustment_brand_ratios

active_dataset: visits_estimation_staging
active_poi_table: activity_poi
active_zipcode_table: activity_zipcode
required_naics_code_table: required_naics_code
required_fk_sgbrands_table: required_fk_sgbrands

source_root_dir: inference_input_json

postgres_conn_id: postgres_gcp_dev

real_visits_staging_dataset: real_visits_staging
expected_overlap_table: expected_overlap


poi_visits_scaled_dataset: poi_visits_scaled
zipcode_visits_scaled_dataset: zipcode_visits_scaled

visits_estimation_dataset: visits_estimation
visits_aggregated_table: visits_observed
visits_aggregated_table_monitor: visits_observed_monitor
max_historical_date_table: max_historical_date

## POI BENCHMARKING
poi_benchmarking_model_dataset: real_visits
poi_benchmarking_model: poi_benchmarking_model
poi_based_model_input_table: poi_based_model_input
poi_benchmarking_training_data_table: poi_benchmarking_training_data



covid_factor_dataset: factoring_data
covid_factor_table: covid_factor

## INFERENCE INPUT - REGRESSORS
inference_input_poi_dataset: visits_estimation_input
regressors_dataset: regressors
covid_collection_table: covid
covid_dictionary_table: covid_dictionary
group_visits_collection_table: group_visits
group_visits_dictionary_table: group_visits_dictionary
holidays_collection_table: holidays
holidays_dictionary_table: holidays_dictionary
weather_collection_table: weather_daily
weather_dictionary_table: weather_dictionary

area_geometries_dataset: area_geometries
states_table: states
cbsa_table: geo_us_boundaries-cbsa

places_dataset: sg_places
places_table: places_dynamic
places_week_array_table: places_week_array_dynamic
places_postgres_dataset: postgres
places_postgres_table: SGPlaceRaw
zipcodes_dataset: area_geometries
zipcodes_table: zipcodes

## INFERENCE INPUT - TESTS
inference_input_zipcode_tests_table: m_zipcode
inference_input_poi_tests_table: m_poi

met_areas_dataset: area_geometries
met_areas_table: met_areas

inference_input_poi_table: poi

restriction_factor_dataset: factoring_data
restriction_factor_table: restriction_factor


staging_dataset: visits_estimation_staging
spurious_places_table: spurious_places

## QUALITY CHECK TESTS
quality_output_previous_table: quality_output_previous
quality_output_table: quality_output
quality_activity_table: quality_activity
quality_activity_zipcode_table: quality_activity_zipcode
quality_monitoring_table: quality_monitoring
sg_base_tables_dataset: sg_base_tables
olvin_base_dataset: olvin_base
naics_code_subcategories_table: naics_code_subcategories

monitoring_quality_check_poi_table: quality_monitoring

active_poi_quality_check_table: activity_poi_quality_check

monitoring_quality_check_poi_test_table: monitoring_quality_check_poi_test
monitoring_quality_check_zipcode_test_table: monitoring_quality_check_zipcode_test


inference_output_poi_table: poi
inference_input_gcs_procedure: storage-prod-olvin-com.procedures.inference_input
inference_bucket: visits-estimation-files-sns-olvin-com
sns_raw_dataset: sns_raw
raw_traffic_formatted_table: raw_traffic_formatted
visits_estimation_model_dataset: visits_estimation_model
grouping_id_table: grouping_id_olvin
grouping_id_gt_table: grouping_id_sns
model_input_olvin_table: model_input_olvin
model_input_table: model_input
model_run_table: model_run
model_output_table: model_output
poi_metadata_table: poi_metadata
model_input_olvin_monitor: model_input_olvin_monitor
events_dataset: events
postgres_batch_dataset: postgres_batch
SGPlaceRaw_table: SGPlaceRaw
holidays_table: holidays
geospatial_output_table: geospatial_output
inference_output_poi_test_table: poi_test


inference_output_covid_restrictions_poi_table: poi_covid_restrictions

## EVENTS
events_holidays_poi_table: events_holidays_poi
events_holidays_group_table: events_holidays_group
tier_events_table: adjustments_events_tier_dates
event_factor_tier_table : adjustments_events_factor_tier
event_factor_places_table: adjustments_events_factor_poi
event_ref_visits_places_table: adjustments_events_ref_visits_poi
events_manual_factors_table: events_manual_factors
events_manual_impact_olvin_category_table: events_manual_impact_olvin_category
events_manual_impact_brand_table: events_manual_impact_brand

## INFERENCE OUTPUT TESTS (WATCHLISTS)
inference_output_poi_tests_table: m_poi

factor_gtvm_visits_estimation_table: factor_gtvm_visits_estimation

hourly_forecast_table: poi_forecast_hourly
hourly_table: poi_hourly
hourly_forecast_zipcode_table: zipcode_forecast_hourly
daily_visits_table: poi_daily
daily_visits_trend_adjustment_table: poi_daily_trend_adjustment
daily_visits_zipcode_table: zipcode_daily


staging_bucket: visits-estimation-files-prod-olvin-com

inference-inputs_main_python_file_uri: gs://visits-estimation-job-files-olvin/runner.py
inference-inputs_python_file_uris:
  - gs://visits-estimation-job-files-olvin/args.py
  - gs://visits-estimation-job-files-olvin/data_prep.py

## METRICS
metrics_dataset: visits_estimation_metrics
visits_volume_visualisations_table: visits_volume_vis
visits_volume_metrics_table: visits_volume_corr
visits_volume_visualisations_test_table: visits_volume_vis_test
visits_volume_metrics_test_table: visits_volume_corr_test
time_series_visualisations_poi_table: time_series_vis_poi
time_series_visualisations_zipcode_table: time_series_vis_zipcode
visits_estimation_visualizations_pipeline: visits_estimation_visualizations
brands_visits_table: brand_agg_visits
ranking_time_series_table: rankings_vis
brand_quality_lost_table: brand_quality_lost
brand_openings_closings_table: brand_openings_closings
brand_hourly_summary_table: brand_hourly_summary
brand_decrease_mom_table: brand_decrease_mom

## GROUND TRUTH DATASET
ground_truth_trend_adjust_output_table: ground_truth_trend_adjust_output
ground_truth_output_core_table: ground_truth_core_output
ground_truth_output_table: ground_truth_output
validation_ground_truth_output_tier_1_table: validation_ground_truth_output_tier_1
validation_ground_truth_output_tier_2_table: validation_ground_truth_output_tier_2
validation_ground_truth_output_tier_4_table: validation_ground_truth_output_tier_4
monthly_visits_class_table: monthly_visits_class
poi_class_business_table: poi_class_business

## RANKINGS
gtvm_dataset: ground_truth_volume_model
gtvm_model_output_table: gtvm_output
rankings_percentile_table: rankings_percentile
rankings_time_series_regulariser_factor: 1.0
monitoring_visits_ranking_table: monitoring_visits_ranking

## SCALING FACTOR TABLE
scaling_factor_table: brand_scaling_factors

dag-sources-regressors-dataforseo-trend: sources-regressors-dataforseo-trend

## LABELS
pipeline_label_value: visits_estimation

sns_composer: prod-sensormatic
sns-prod-composer-name: prod-sensormatic
sns_composer_location: europe-west1
sns-prod-composer-location: europe-west1
cross_project_service_account: cross-project-composer-worker@sns-vendor-olvin-poc.iam.gserviceaccount.com
cross-project-composer-worker-service-account: cross-project-composer-worker@sns-vendor-olvin-poc.iam.gserviceaccount.com
sns_dags_status_table: sensormatic_dags_status
gtvm_metrics_pipeline: visits_estimation_gtvm_accuracy
trend_adjustment_pipeline: visits_estimation_trend_adjustment

accessible_by_sns_dataset: accessible_by_sns

smc_metrics_dataset: sns_metrics
pois_table: gtvm_output_pois
groups_table: gtvm_output_groups
gtvm_accuracy_table: visits_estimation_accuracy
sns_latency_days: 10

accessible_by_olvin_dataset: accessible_by_olvin
poi_matching_dataset: poi_matching
smc_production_dates_table: smc_production_dates

postgres_dataset: postgres
sgplaceraw_table: SGPlaceRaw
sgbrandraw_table: SGBrandRaw
zipcoderaw_table: ZipCodeRaw

# Adjustments
openings_adjustment_week_array_table: openings_adjustment_week_array
openings_adjustment_table: openings_adjustment
adjustments_days_with_zero_visits: adjustments_closing_days_with_zero_visits
adjustments_closing_days_logic: adjustments_closing_days_logic
adjustments_closings_output: adjustments_closings_output
adjustments_closings_open_manual_table: adjustments_closings_open_manual
adjustments_covid_output_table: adjustments_covid_output
adjustments_events_output: adjustments_events_output
adjustment_output_zipcode_table: adjustment_output_zipcode
adjustments_events_output_table: adjustments_events_output
adjustments_events_usage_table: adjustments_events_usage
adjustments_hourly_geo_visits_poi: adjustments_hourly_geo_visits_poi
adjustments_hourly_geo_visits_grouped: adjustments_hourly_geo_visits_grouped
adjustments_volume_output_table: adjustments_volume_output
adjustments_places_dynamic_output_table: adjustments_places_dynamic_output
adjustments_places_dynamic_output: adjustments_places_dynamic_output
adjustments_output_hourly_table: adjustments_output_hourly
adjustments_output_table: adjustments_output
visits_aggregated_dataset: poi_aggregated_visits
places_dataset: sg_places
manual_closing_brands_table: manual_closing_brands

# General
poi_class_table: poi_class
class_pois_sns_table: class_pois_sns
class_pois_olvin_table: class_pois_olvin
list_sns_pois_table: list_sns_pois
monthly_visits_class_table: monthly_visits_class
events_dataset: events
holidays: holidays
v_prod_matching_extended_table: v_prod_matching_extended
v_raw_traffic_metadata_table: v_raw_traffic_metadata
theta: 0.687341950


# Output
visits_estimation_output_dataset: visits_estimation_output
SGPlaceMonthlyVisitsRaw_table: SGPlaceMonthlyVisitsRaw
SGPlaceDailyVisitsRaw_table: SGPlaceDailyVisitsRaw
SGPlaceRanking_table: SGPlaceRanking
ZipCodeDailyVisitsRaw_table: ZipCodeDailyVisitsRaw
SGPlaceHourlyAllVisitsRaw_table: SGPlaceHourlyAllVisitsRaw
SGPlaceHourlyVisitsRaw_table: SGPlaceHourlyVisitsRaw
ZipCodeHourlyVisitsRaw_table: ZipCodeHourlyVisitsRaw
SGPlacePatternVisitsRaw_table: SGPlacePatternVisitsRaw
places_postgres_batch_dataset: postgres_batch

# SNS
sns_raw_dataset: sns_raw
raw_traffic_formatted_table: raw_traffic_formatted
factor_tier_table: adjustments_events_factor_tier
tier_dates_table: adjustments_events_tier_dates
visits_estimation_ground_truth_supervised_dataset: visits_estimation_ground_truth_supervised

# MANUAL INPUT TABLES
ground_truth_manual_yearly_seasonalities_table: ground_truth_manual_yearly_seasonalities
ground_truth_manual_weekly_seasonalities_table: ground_truth_manual_weekly_seasonalities

# STATIC FEATURES
static_features_dataset: static_features

# UNBIASING
yearly_seasonality_table: yearly_seasonality
yearly_seasonality_brand_table: yearly_seasonality_brand
weekly_seasonality_table: weekly_seasonality
weekly_seasonality_brand_table: weekly_seasonality_brand

poi_list_yearly_seasonality_unbiasing_table: poi_list_yearly_seasonality_unbiasing
ground_truth_year_season_corrected_output_table: ground_truth_year_season_corrected_output
poi_list_weekly_seasonality_unbiasing_table: poi_list_weekly_seasonality_unbiasing

