
project: storage-prod-olvin-com
staging_bucket: postgres-database-tables-staging
postgres_dev_conn_id: postgres_gcp_dev
postgres_staging_conn_id: postgres_gcp_staging
vm_zone: us-east4-b
tables_dataset: postgres_mv_rt
tables_list:
  - SGPlaceDailyVisitsRaw
  - SGPlaceMonthlyVisitsRaw
  - SGPlaceRanking