# FEEDS
public_feeds_dataset: public_data_feeds_type_2
public_feeds_finance_dataset: public_data_feeds_type_2_finance
public_feeds_staging_dataset: public_data_feeds_type_2_staging
store_visits_table: store_visits
store_visits_trend_table: store_visits_trend
store_visitors_table: store_visitors
placekeys_table: placekeys
placekeys_temp_table: placekeys_temp
placekeys_snapshot_table: placekeys_snapshot_table


# SAFEGRAPH
places_dataset: sg_places
places_dynamic_table: places_dynamic
places_history_table: places_history
base_tables_dataset: sg_base_tables
non_sensitive_naics_codes_table: non_sensitive_naics_codes

# OLVIN
postgres_batch_dataset: postgres_batch
sgplaceraw_table: SGPlaceRaw
sgbrandraw_table: SGBrandRaw

# FEED DAGS
store_visits_trend_feed: products-feeds-stability-store-visits-trend
store_visits_feed: products-feeds-stability-store-visits
store_visitors_feed: products-feeds-stability-store-visitors

# GCS BUCKET
raw_feed_bucket: pby-public-data-feed-type-2
raw_feed_finance_bucket: pby-public-data-feed-type-2-finance
dataproc_region: europe-west1
versioning_bucket: pby-product-p-gcs-euwe1-data_feeds_base_table_versions