sns-raw-dataset: sns_raw
sns-raw-traffic-formatted-table: raw_traffic_formatted

accessible-by-olvin-dataset: accessible_by_olvin
visits-estimation-metrics-dataset: visits_estimation_metrics
metrics-table: temp_daily_visits_metrics

postgres-batch-dataset: postgres_batch
sgplacedailyvisitsraw-table: SGPlaceDailyVisitsRaw

visits-estimation-supervised-dataset: visits_estimation_ground_truth_supervised_staging
list-sns-pois-table: list_sns_pois

accessible-by-sns-dataset: accessible_by_sns
yoy-dates-nrf-calendar-table: yoy_dates_nrf_calendar