# FEEDS
public_feeds_dataset: public_data_feeds_type_1
public_feeds_finance_dataset: public_data_feeds_type_1_finance
public_feeds_staging_dataset: public_data_feeds_type_1_staging
alphamap_bucket: alphamap-feed
feeds_staging_gcs_bucket: pby-product-p-gcs-euwe1-datafeed
feeds_staging_gcs_no_pays_bucket: pby-product-p-gcs-euwe1-datafeed-no-pays
azure_pby_push_file_name: azure-pby-push
feeds_staging_gcs_daily_bucket: pby-product-p-gcs-euwe1-datafeed-daily-staging
feeds_keys_gcs_bucket: pby-product-p-gcs-euwe1-datafeed-keys
feeds_staging_aws_bucket: pby-public-data-feed-staging
feeds_staging_aws_bucket_requester_pays_off: pby-public-data-feed-staging-no-pays
feeds_staging_aws_bucket_man_group: pby-public-data-feed-man-group
store_visits_table: store_visits
store_visits_trend_table: store_visits_trend
store_visitors_table: store_visitors
placekeys_table: placekeys
dataproc_region: europe-west1
# FEED DAGS
store_visits_trend_feed: products-feeds-accuracy-store-visits-trend
store_visits_feed: products-feeds-accuracy-store-visits
store_visitors_feed: products-feeds-accuracy-store-visitors
placekeys_feed: products-feeds-accuracy-placekeys

store_visits_daily_table: store_visits_daily


client_name_list:
- man_group
- client_2