DECLARE date_tag STRING;
SET date_tag = CONCAT(
    CAST(CURRENT_DATE() AS STRING format('YYYY')),
    '-',
    CAST(CURRENT_DATE() AS STRING format('MM')),
    '-',
    '01'
);
  
MERGE INTO 
        `{{ params['project'] }}.{{ params['staging_data_dataset'] }}.{{ params['all_places_table'] }}` sg_all
    USING 
        `{{ params['project'] }}.{{ params['staging_data_dataset'] }}.sg_places` places
        ON 
            sg_all.sg_id=places.sg_id 
    WHEN MATCHED THEN
        UPDATE SET 
            fk_parents_sg=places.fk_parents,
            fk_sgbrands=places.fk_sgbrands,
            name=places.name,
            brands=places.brands,
            top_category=places.top_category,
            sub_category=places.sub_category,
            naics_code=places.naics_code,
            latitude=places.latitude,
            longitude=places.longitude,
            street_address=places.street_address,
            city=places.city,
            region=places.region,
            postal_code=CAST(places.postal_code AS STRING),
            open_hours=places.open_hours,
            category_tags=places.category_tags,
            polygon_wkt=places.polygon_wkt,
            polygon_class=places.polygon_class,
            enclosed=places.enclosed,
            iso_country_code=places.iso_country_code,
            region_id=places.region_id,
            long_lat_point=places.long_lat_point,
            simplified_polygon_wkt=places.simplified_polygon_wkt,
            simplified_wkt_10_buffer=places.simplified_wkt_10_buffer,
            standalone_bool=places.standalone_bool,
            child_bool=places.child_bool,
            parent_bool=places.parent_bool,
            naics_industry=places.naics_industry,
            industry=places.industry,
            polygon_area_sq_ft=places.polygon_area_sq_ft,
            phone_number=CAST(places.phone_number AS INT64),
            is_synthetic=places.is_synthetic,
            includes_parking_lot=places.includes_parking_lot,
            timezone=places.timezone,
            opened_on=CAST(places.opened_on AS STRING),
            closed_on=CAST(places.closed_on AS STRING),
            last_seen=CAST(date_tag as DATE)
    WHEN NOT MATCHED THEN
        INSERT (
            sg_id,
            fk_parents_sg,
            fk_sgbrands,
            name,
            brands,
            top_category,
            sub_category,
            naics_code,
            latitude,
            longitude,
            street_address,
            city,
            region,
            postal_code,
            open_hours,
            category_tags,
            polygon_wkt,
            polygon_class,
            enclosed,
            iso_country_code,
            region_id,
            long_lat_point,
            simplified_polygon_wkt,
            simplified_wkt_10_buffer,
            standalone_bool,
            child_bool,
            parent_bool,
            naics_industry,
            industry,
            polygon_area_sq_ft,
            phone_number,
            is_synthetic,
            includes_parking_lot,
            timezone,
            opened_on,
            closed_on,
            first_seen,
            last_seen
        )
        VALUES(
            places.sg_id,
            places.fk_parents,
            places.fk_sgbrands,
            places.name,
            places.brands,
            places.top_category,
            places.sub_category,
            places.naics_code,
            places.latitude,
            places.longitude,
            places.street_address,
            places.city,
            places.region,
            CAST(places.postal_code AS STRING),
            places.open_hours,
            places.category_tags,
            places.polygon_wkt,
            places.polygon_class,
            places.enclosed,
            places.iso_country_code,
            places.region_id,
            places.long_lat_point,
            places.simplified_polygon_wkt,
            places.simplified_wkt_10_buffer,
            places.standalone_bool,
            places.child_bool,
            places.parent_bool,
            places.naics_industry,
            places.industry,
            places.polygon_area_sq_ft,
            CAST(places.phone_number AS INT64),
            places.is_synthetic,
            places.includes_parking_lot,
            places.timezone,
            CAST(places.opened_on AS STRING),
            CAST(places.closed_on AS STRING),
            CAST(date_tag as DATE),
            CAST(date_tag as DATE)
        )