# FEEDS
public_feeds_dataset: public_data_feeds_type_2
public_feeds_finance_dataset: public_data_feeds_type_2_finance
public_feeds_staging_dataset: public_data_feeds_type_2_staging
dewey_bucket: dewey-feed
feeds_staging_gcs_bucket: pby-product-p-gcs-euwe1-datafeed
feeds_staging_gcs_no_pays_bucket: pby-product-p-gcs-euwe1-datafeed-no-pays
feeds_keys_gcs_bucket: pby-product-p-gcs-euwe1-datafeed-keys
feeds_staging_aws_bucket: pby-public-data-feed-staging
feeds_staging_aws_bucket_man_group: pby-public-data-feed-man-group
store_visits_table: store_visits
store_visits_trend_table: store_visits_trend
store_visitors_table: store_visitors
placekeys_table: placekeys
dataproc_region: europe-west1
data_feeds_project: data-feed-olvin
# FEED DAGS
store_visits_trend_feed: products-feeds-stability-store-visits-trend
store_visits_feed: products-feeds-stability-store-visits
store_visitors_feed: products-feeds-stability-store-visitors
placekeys_feed: products-feeds-stability-placekeys

# CLIENT BUCKETS
maiden_century_bucket: mc-ext-vendor-passby
quantcube_bucket: q3-ext-trial-poi