storage-prod: storage-prod-olvin-com
postgres_dataset: postgres
visitor_brand_destinations_metrics_dataset: visitor_brand_destinations_metrics
monitoring_market_table: monitoring_market_analysis
market_analysis_table: BrandMallLocations
brands_table: SGBrandRaw
places_table: SGPlaceRaw
census_table: census_tracts
area_geometries_dataset: area_geometries

project_id: storage-prod-olvin-com
staging_bucket: postgres-database-tables-staging
postgres_conn_id: postgres_gcp_dev

pipeline_label_value: void_market_preprocess

