predicthq_dataset: predicthq_test
regressors_dataset: regressors
regressors_staging_dataset: regressors_staging
preprocessed_daily_data_table: preprocessed_daily_events_data
full_data_table: predicthq_events_full_data_20220519
regressors_table: predicthq_events_collection
daily_data_table : daily_events_data

# API_URL: https://api.predicthq.com/v1/events
# TODO: add to file with params
predicthq_image: europe-west1-docker.pkg.dev/storage-prod-olvin-com/apis/predicthq:latest

regressors_metrics_dataset: regressors_metrics
predicthq_events_agg_table: predicthq_events_aggregated

test_compilation_dataset: test_compilation
test_results_table: regressors_tests
pipeline_label_value: regressors_events

s2_token_size: 13
