sns_project: sns-vendor-olvin-poc
cross_project_service_account: cross-project-composer-worker@sns-vendor-olvin-poc.iam.gserviceaccount.com

accessible_by_sns_dataset: accessible_by_sns
accessible_by_olvin_dataset: accessible_by_olvin
# poi_visits_dataset
poi_visits_dataset: smc_poi_visits

# poi_scaled_data_dataset
poi_visits_scaled_dataset: smc_poi_visits_scaled_block_groundtruth
smc_poi_visits_staging_dataset: smc_poi_visits_staging
post_block_1_scaling_procedure: procedures.smc_post_block_1_scaling
block_1_scaling_procedure: procedures.post_smc_cluster_backfill_block_1_scaling

# smc_metrics_dataset
smc_metrics_dataset: smc_metrics
day_stats_visits_table: day_stats_visits
day_stats_visits_scaled_table: day_stats_visits_scaled
time_series_analysis_vis_block_groundtruth_table: time_series_analysis_vis_block_groundtruth
smc_day_stats_visits_scaled_procedure: procedures.smc_daily_stats_visits_scaled

# metrics_dataset
metrics_dataset: metrics
day_stats_geohits_table: day_stats_geohits
day_stats_clusters_table: day_stats_clusters

# quality_dataset
geoscaling_dataset: smc_geoscaling
quality_dataset: smc_quality
model_input_complete_table: model_input
geoscaling_model: geoscaling_model
block_1_output_table: block_1_output
quality_ml_input_procedure: procedures.geoscaling_ml_input

# functions_dataset
functions_dataset: functions

# base_table_dataset
base_table_dataset: sg_base_tables
naics_code_subcategories: naics_code_subcategories
sg_categories_match_old_table: sg_categories_match

# demographics_dataset
demographics_dataset: static_demographics_data_v2
zipcode_demographics_table: original_zipcode_demographics_v2

# device_zipcodes_dataset
device_zipcodes_dataset: device_zipcodes_v2

# places_data_dataset
smc_places_dataset: smc_sg_places
places_filter_table: places_filter
places_data_table: places_dynamic
footprints_m_view: places_and_footprints

# new_regressors_dataset
original_regressors_dataset: regressors
new_regressors_dataset: smc_regressors
weather_collection_table: weather
weather_dictionary: weather_dictionary
holidays_collection_table: holidays
holidays_dictionary: holidays_dictionary
covid_collection_table: covid
covid_dictionary_table: covid_dictionary
covid_dictionary_zipcode_table: covid_dictionary_zipcode

# visit_share_dataset
visit_share_dataset: smc_visits_share
visits_share_model: tf_classifier
prior_distance_function: prior_distance_parameters

# daily estimation dataset
smc_daily_estimation_dataset: smc_daily_estimation
grouped_daily_olvin_table: grouped_daily_olvin
poi_list_table: poi_list
daily_factor_table: daily_factor
daily_estimation_runs_table: daily_estimation_runs

# real_visits_dataset
real_visits_dataset: smc_real_visits
real_visits_grid_factors_table: real_visits_grid_factors
pre_scaling_poi_based_table: pre_scaling_poi_based
ml_factors_poi_based_table: ml_factors_poi_based
granularity_grid_real_visits: 8

# ground_truth_volume_model_dataset
ground_truth_volume_model_dataset: smc_ground_truth_volume_model
ground_truth_model_factor_per_poi_table: factor_per_poi

# areas_dataset
areas_dataset: area_geometries
zipcodes_table: zipcodes

# raw_visits_dataset
raw_visits_dataset: device_clusters

# device_homes_dataset
device_homes_dataset: device_homes

# device_clusters_dataset
device_clusters_dataset: device_clusters