create or replace table `{{ var.value.env_project }}.{{ params['regressors_dataset'] }}.{{ params['holidays_regressors_collection_table'] }}` copy `{{ params['sns_project'] }}.{{ params['accessible_by_olvin_dataset'] }}.{{ params['regressors_dataset'] }}_{{ params['holidays_regressors_collection_table'] }}`;
create or replace table `{{ var.value.env_project }}.{{ params['events_dataset'] }}.{{ params['holidays_regressors_collection_table'] }}` copy `{{ params['sns_project'] }}.{{ params['accessible_by_olvin_dataset'] }}.{{ params['events_dataset'] }}_{{ params['holidays_regressors_collection_table'] }}`;

create or replace table `{{ var.value.env_project }}.{{ params['regressors_dataset'] }}.{{ params['holidays_dictionary_table'] }}` copy `{{ params['sns_project'] }}.{{ params['accessible_by_olvin_dataset'] }}.{{ params['regressors_dataset'] }}_{{ params['holidays_dictionary_table'] }}`;
create or replace table `{{ var.value.env_project }}.{{ params['events_dataset'] }}.{{ params['holidays_dictionary_table'] }}` copy `{{ params['sns_project'] }}.{{ params['accessible_by_olvin_dataset'] }}.{{ params['events_dataset'] }}_{{ params['holidays_dictionary_table'] }}`;

create or replace table `{{ var.value.env_project }}.{{ params['regressors_dataset'] }}.{{ params['holidays_dictionary_zipcode_table'] }}` copy `{{ params['sns_project'] }}.{{ params['accessible_by_olvin_dataset'] }}.{{ params['regressors_dataset'] }}_{{ params['holidays_dictionary_zipcode_table'] }}`;
create or replace table `{{ var.value.env_project }}.{{ params['events_dataset'] }}.{{ params['holidays_dictionary_zipcode_table'] }}` copy `{{ params['sns_project'] }}.{{ params['accessible_by_olvin_dataset'] }}.{{ params['events_dataset'] }}_{{ params['holidays_dictionary_zipcode_table'] }}`;

create or replace table `{{ var.value.env_project }}.smc_{{ params['regressors_dataset'] }}.{{ params['holidays_dictionary_table'] }}` copy `{{ params['sns_project'] }}.{{ params['accessible_by_olvin_dataset'] }}.{{ params['regressors_dataset'] }}_{{ params['holidays_dictionary_table'] }}`;
create or replace table `{{ var.value.env_project }}.smc_{{ params['events_dataset'] }}.{{ params['holidays_dictionary_table'] }}` copy `{{ params['sns_project'] }}.{{ params['accessible_by_olvin_dataset'] }}.{{ params['events_dataset'] }}_{{ params['holidays_dictionary_table'] }}`;

create or replace table `{{ var.value.env_project }}.smc_{{ params['regressors_dataset'] }}.{{ params['holidays_dictionary_zipcode_table'] }}` copy `{{ params['sns_project'] }}.{{ params['accessible_by_olvin_dataset'] }}.{{ params['regressors_dataset'] }}_{{ params['holidays_dictionary_zipcode_table'] }}`;
create or replace table `{{ var.value.env_project }}.smc_{{ params['events_dataset'] }}.{{ params['holidays_dictionary_zipcode_table'] }}` copy `{{ params['sns_project'] }}.{{ params['accessible_by_olvin_dataset'] }}.{{ params['events_dataset'] }}_{{ params['holidays_dictionary_zipcode_table'] }}`;


create or replace table `{{ var.value.env_project }}.{{ params['regressors_dataset'] }}.{{ params['group_visits_collection_table'] }}` copy `{{ params['sns_project'] }}.{{ params['accessible_by_olvin_dataset'] }}.{{ params['regressors_dataset'] }}_{{ params['group_visits_collection_table'] }}`;
create or replace table `{{ var.value.env_project }}.{{ params['regressors_dataset'] }}.{{ params['group_visits_dictionary_table'] }}` copy `{{ params['sns_project'] }}.{{ params['accessible_by_olvin_dataset'] }}.{{ params['regressors_dataset'] }}_{{ params['group_visits_dictionary_table'] }}`;
create or replace table `{{ var.value.env_project }}.{{ params['regressors_dataset'] }}.{{ params['group_visits_dictionary_zipcode_table'] }}` copy `{{ params['sns_project'] }}.{{ params['accessible_by_olvin_dataset'] }}.{{ params['regressors_dataset'] }}_{{ params['group_visits_dictionary_zipcode_table'] }}`;