project: storage-prod-olvin-com
dev_project: storage-dev-olvin-com

raw_visits_dataset: device_clusters
device_homes_dataset: device_homes
static_demographics_data_dataset: static_demographics_data_v2
static_demographics_data_v2_dataset: static_demographics_data_v2
zipcode_points_table: zipcode_points
zip4ll_full_table: zip4ll_full
device_zipcodes_dataset: device_zipcodes
device_zipcodes_v2_dataset: device_zipcodes_v2
poi_visits_scaled_dataset: poi_visits_scaled
zipcode_demographics_table: original_zipcode_demographics_v2
MonthlyPersona_dataset: personas
Search_dataset: consumer_search
Neighbourhood_table: neighbourhood
MetAreaCategory_table: category
NeighbourhoodCategory_table: neighbourhood_category
MetAreaChain_table: chain
CSDChain_table: csd_chain
Consumer_table: consumer_search
dpc_staging_bucket: demographics-files-prod-olvin-com
postgres_conn_id: postgres_gcp_dev
postgres_conn_id_azure: postgres_azure_dev
area_geometries_dataset: area_geometries
neighbourhoods_table: neighbourhoods
csds_table: csds
zipcodes_table: zipcodes

pipeline_label_value: demographics_pipeline