storage-prod: storage-prod-olvin-com
storage-dev: storage-dev-olvin-com
postgres_dataset: postgres
visitor_brand_dest_table: SGPlaceVisitorBrandDestinations
brands_table: SGBrandRaw
places_table: SGPlaceRaw
visit_dataset: poi_visits_scaled
device_zipcodes_v2_dataset: device_zipcodes_v2

project_id: storage-prod-olvin-com
staging_bucket: postgres-database-tables-staging
postgres_conn_id: postgres_gcp_dev

pipeline_label_value: cameo_categories

test_compilation_dataset: test_compilation
monthly_update_table: monthly_update

static_demographics_dataset: static_demographics_data_v2
zipcode_demographics_table: zipcode_demographics
cameo_staging_dataset: cameo_staging
cameo_visits_table: cameo_visits
cameo_categories_processed_table: cameo_categories_processed
cameo_ema_24_table: cameo_ema_24
smoothed_transition_table: smoothed_transition

ground_truth_volume_dataset: ground_truth_volume_model
brand_scaling_factors_table: brand_scaling_factors
cameo_table: SGPlaceCameoRaw
cameo_monthly_table: SGPlaceCameoMonthlyRaw

cameo_monitoring_check_table: cameo_monitoring_check