# gcs data locations
sg_data_bucket: safegraph-raw-data-olvin-com
sg_data_blobs: imports/core_poi-geometry
sg_core_poi_file_name: core_poi-geometry-part*
sg_brands_data_blobs: imports/brand_info
sg_spend_data_blobs: imports/spend
sg_spend_patterns_blobs: spend_patterns
sg_transaction_panel_summary_blobs: transaction_panel_summary
sg_spend_data_file_name: part-*
sg_lineage_api_response_folder: lineage_api_response


# bigquery projects
project: storage-prod-olvin-com
storage_project_id: storage-prod-olvin-com
storage_dev: storage-dev-olvin-com

# bigquery datasets
places_data_dataset: sg_places
staging_data_dataset: sg_places_staging
raw_data_dataset: sg_raw_data
base_tables_data_dataset: sg_base_tables
metrics_data_dataset: sg_places_metrics
postgres_data_dataset: postgres
geometry_dataset: area_geometries

# bigquery tables
different_digit_naics_code_table: different_digit_naics_code
non_sensitive_naics_codes_table: non_sensitive_naics_codes
all_places_table: places_history
all_brands_table: brands_history
dynamic_places_table: places_dynamic
dynamic_brands_table: brands_dynamic
week_array_table: places_week_array_dynamic
places_postgres_table: SGPlaceRaw_dynamic
brands_postgres_table: SGBrandRaw_dynamic
raw_metadata_table: sg_raw_metadata
raw_metadata_US_table: sg_raw_US_metadata
places_metadata_table: sg_places_metadata
places_placekey_stats_table: sg_places_placekey_stats
brand_metadata_table: sg_brand_metadata
timezones_table: worldwide_timezones
brand_urls_table: brand_urls
duplicates_table: duplicates_to_deactivate
amend_polygons_table: polygons_to_amend
site_lineage_table: site_id_lineage
ideal_dynamic_places_table: ideal_places_dynamic
spend_patterns_table: spend_patterns
transaction_panel_summary_table: transaction_panel_summary
openings_adjustment_table: openings_adjustment


# api credentials
api_url: https://api.placekey.io/v1/lineage
api_key: vx0RhFbZnXRAnSben7qKPOb0iQwr998I

history_backup_bucket: places-history-backup

# docker images
# TODO: replace with params in file...
lineage_api_image: europe-west1-docker.pkg.dev/storage-prod-olvin-com/apis/lineage:latest