MERGE INTO
  -- `olvin-sandbox-20210203-0azu4n.jayson_test.full_data_20220503` t1
  `{{ var.value.env_project }}.{{ params['regressors_dataset'] }}.{{ params['full_data_table'] }}` t1
USING
  -- `olvin-sandbox-20210203-0azu4n.jayson_test.preprocessed_updated_data_20220504` t2
  `{{ var.value.env_project }}.{{ params['regressors_staging_dataset'] }}.{{ params['preprocessed_daily_data_table'] }}` t2
  ON
    t1.id=t2.id
WHEN MATCHED THEN
  UPDATE SET
    t1.duplicate_of_id = t2.duplicate_of_id,
    t1.relevance= t2.relevance,
    t1.updated= t2.updated,
    t1.title= t2.title,
    t1.labels= t2.labels,
    t1.category= t2.category,
    t1.description = t2.description,
    t1.start = t2.start,
    t1.end =t2.end,
    t1.predicted_end = t2.predicted_end,
    t1.timezone = t2.timezone,
    t1.duration = t2.duration,
    t1.country =t2.country,
    t1.lat =t2.lat,
    t1.lon=t2.lon,
    t1.geo = t2.geo,
    t1.impact_patterns = t2.impact_patterns,
    t1.scope = t2.scope,
    t1.rank = t2.rank,
    t1.local_rank = t2.local_rank,
    t1.aviation_rank = t2.aviation_rank,
    t1.phq_attendance = t2.phq_attendance,
    t1.state= t2.state,
    t1.cancelled =t2.cancelled,
    t1.postponed = t2.postponed,
    t1.deleted_reason =t2.deleted_reason,
    t1.first_seen = t2.first_seen,
    t1.place_hierarchies = t2.place_hierarchies,
    t1.private = t2.private,
    t1.brand_safe = t2.brand_safe
  WHEN NOT MATCHED THEN
    INSERT(
      id,
      duplicate_of_id,
      relevance,
      updated,
      title,
      labels,
      category,
      description,
      start,
      `end`,
      predicted_end,
      timezone,
      duration,
      country,
      lat,
      lon,
      geo,
      impact_patterns,
      scope,
      `rank`,
      local_rank,
      aviation_rank ,
      phq_attendance,
      state,cancelled,
      postponed,
      deleted_reason,
      first_seen,
      place_hierarchies,
      private,
      brand_safe
    )
    VALUES(
      t2.id,
      t2.duplicate_of_id,
      t2.relevance,
      t2.updated,
      t2.title,
      t2.labels,
      t2.category,
      t2.description,
      t2.start,
      t2.`end`,
      t2.predicted_end,
      t2.timezone,
      t2.duration,
      t2.country,
      t2.lat,
      t2.lon,
      t2.geo,
      t2.impact_patterns,
      t2.scope,
      t2.`rank`,
      t2.local_rank,
      t2.aviation_rank ,
      t2.phq_attendance,
      t2.state,
      t2.cancelled,
      t2.postponed,
      t2.deleted_reason,
      t2.first_seen,
      t2.place_hierarchies,
      t2.private,
      t2.brand_safe
    )
