# visits_dataset
visits_dataset: poi_visits

# smc_visits_dataset
smc_visits_dataset: smc_poi_visits

# smc_places_dataset
smc_places_dataset: smc_sg_places
places_table: places_dynamic
week_array_table: places_week_array_dynamic
footprints_m_view: places_and_footprints

# device_clusters_dataset
device_clusters_dataset: device_clusters

# functions_dataset
functions_dataset: functions