#storage_project: storage-dev-olvin-com
#compute_project: olvin-sandbox-20210203-0azu4n #compute-prod-olvin-com

project: storage-prod-olvin-com
storage_project: storage-prod-olvin-com
networks_dataset: networks
networks_staging_dataset: networks_staging
networks_metrics_dataset: networks_metrics

#Historical
mode: monthly #historical

# Miscellaneous
sg_places_dataset: sg_places
sg_places_table: 20211101

# SAMPLE vs ALL DATA
is_sample: False

# INPUT LINK PREDICTION
poi_representation_dataset: networks_staging
poi_representation_table: node_features_raw

poi_visits_project: storage-prod-olvin-com
poi_visits_dataset: poi_visits_scaled #networks_staging
# poi_visits_scaled_table: poi_visits_scaled_sample_historical #*
device_homes_project: storage-prod-olvin-com
device_homes_dataset: device_homes #networks_staging
# device_homes_table: device_homes_sample_historical #*
distance_home_threshold: 30
full_visits_table: full_visits
all_combinations_table: all_combinations
observed_connections_edges_table: observed_connections_edges

node_features_historical_table: node_features_historical
node_features_raw_table: node_features_raw
node_features_all_table: node_features_all
node_features_table: node_features #node_features_sample

places_postgres_dataset: postgres
postgres_dataset: postgres
places_postgres_table: SGPlaceRaw
activity_table: SGPlaceActivity

sg_base_tables_dataset: sg_base_tables
non_sensitive_naics_codes_table: non_sensitive_naics_codes

## Metrics

input_weight_vs_features_table: input_weight_vs_features
output_weight_vs_features_table: output_weight_vs_features


# LINK PREDICTION

nodes_folder: node_features
observed_connections_folder: observed_connections_edges

# instance_name: networks-2
instance_zone: europe-west1-b


# OUTPUT LINK PREDICTION
neo4j_bucket: neo4j-data-prod-olvin-com

predicted_edges_table: estimated_connections_neo4j_id

neo4j_id_table: neo4j_id
predicted_mapping_id_table: estimated_connections
mixed_conn_table: mixed_connections

max_miles: 100
topk: 100
estimated_connections_table_sample: estimated_k_connections_transformed_sample
estimated_connections_table: estimated_k_connections_transformed
postgres_connection_table: SGPlaceConnection

networks_vm: networks-prod

second_deg_conn_table: estimated_connections_second_deg
smooth_conn_table: estimated_smooth_conn


postgres_conn_id: postgres_gcp_dev
early_computation_days: 6

pipeline_label_value: networks_new

visits_pipeline: visits_daily

















# all_historical_predict_table: all_historical_predict
# all_transform_predict_table: all_transform_predict
# neo4j_id_table: neo4j_id
# predict_edges_postgres_json_table: predict_postgres_json
# last_connection_table: last_connection
# final_estimated_connections_table: final_estimated_connections
# last_connections_table: last_connection



# # POSTGRES FORMATTING
# connections_all_table: connections_all
# chain_connections_all_table: chain_connections_all
# journeys_all_table: journeys_all



#Miscellaneous


#device_visits_dataset: networks_staging
#device_visits_table: device_visits_sample

#journeys_edges_table: journeys_edges
#estimated_journeys_table: estimated_journeys

#nodes_features_table_intermediate: nodes_features_intermediate

# input data for 6 months historical  for poi scaled data {project: storage-prod-olvin-com}
# storage_prod_project_6_month: storage-prod-olvin-com
# poi_visits_historical_dataset: poi_visits_scaled_met_areas
# poi_visits_historical_table: 2021
# #input data for 6 months historical  for device home {project: storage-prod-olvin-com}}
# device_homes_historical_dataset: device_homes
# device_home_historical_table: 2021
# #input data for 6 months historical  for device from device clusters {project: storage-prod-olvin-com}}
# device_visits_historical_dataset: device_clusters
# device_visits_historical_table: 2021
# #input data for 6 months historical  nodes features from dev project {project: storage-dev-olvin-com}}
# node_features_project: storage-dev-olvin-com
# node_features_dataset: networks_staging
# node_features: node_features_historical