project: storage-prod-olvin-com
# REGRESSORS
regressors_dataset: smc_regressors
dictionary_table: predicthq_events_dictionary

# PLACES
sg_places_dataset: sg_places
sg_places_table: places_dynamic
sg_places_reviews_table: places_reviews

visits_estimation_dataset: visits_estimation
sns_pois_table: list_sns_pois

places_api_goog_data_bucket: places-api-goog-olvin
places_api_goog_reviews_folder: reviews

# IMAGE CONFIG
reviews_image: europe-west1-docker.pkg.dev/storage-prod-olvin-com/apis/reviews:latest
api_key: AIzaSyAicqQ7CICe09_gMH3ShVA838Ju-axgxbk