name: Run black

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
    black-lint:
        runs-on: ubuntu-latest
        name: black Lint
        steps:
        - uses: actions/checkout@v3
          with:
            ref: ${{ github.head_ref }}
        - uses: psf/black@stable
          with:
            options: "--check --diff"
            use_pyproject: false