name: Run flake8
on:
    pull_request:
      branches:
        - master
    push:
      branches:
        - master

jobs:
    flake8-lint:
        runs-on: ubuntu-latest
        name: Lint
        steps:
            - uses: actions/checkout@v3
              with:
                ref: ${{ github.head_ref }}
            - name: Set up Python environment
              uses: actions/setup-python@v4
              with:
                python-version: "3.11"
            - name: flake8 Lint
              uses: py-actions/flake8@v2
              with:
                ignore: "E203"
                max-line-length: "150"