---
name: Linting

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      # check-out repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      # install poetry
      - name: Install poetry
        run: pipx install poetry==1.2.0
      # install requirements
      - name: Install requirements
        run: poetry install --only black isort flake8
      # Add new steps to run black, isort, and flake8
      - name: Run black
        run: poetry run black .
      - name: Run isort
        run: poetry run isort .
      - name: Run flake8
        run: poetry run flake8 .
