---
name: Linting

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      # check-out repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      # install poetry
      - name: Install poetry
        run: pipx install poetry==1.2.0
      # install requirements (including dev dependencies)
      - name: Install black
        run: poetry install --only black
      - name: Install isort
        run: poetry install --only isort
      - name: Install flake8
        run: poetry install --only flake8
      # run linters
      - name: Run black
        run: poetry run black .
      - name: Run isort
        run: poetry run isort .
      - name: Run flake8
        run: poetry run flake8 .
