name: Semantic Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  main:
    name: Check pull request title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5.5.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Type abbreviation comments:
          # feat -> feature
          types: |
            hotfix
            coldfix
            feature
            refactor
          # Scope abbreviation comments:
          scopes: |
            dag
            git
            poetry
          # The pull request's title should be fulfilled the following pattern:
          #
          #     [<type>][<optional scope>] <description>
          #
          # ... where valid types and scopes can be found above; for example:
          #
          #     [fix][test] flaky test V1_ProxyAuthenticationTest.anonymousSocketTest
          headerPattern: '^\[(\w*?)\](?:\[(.*?)\])?(?:\s*)(.*)$'
          headerPatternCorrespondence: type, scope, subject