name: Deploy READMEs to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install markdown-to-html converter
        run: npm install -g markdown-to-html

      - name: Convert READMEs to HTML and move to docs folder
        run: |
          mkdir docs
          find . -name 'README.md' -exec sh -c 'markdown-to-html -f html5 {} > docs/$(dirname {}).html' \;

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs