name: Ruff Lint
on: push
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
            args: 'check --config pyproject.toml --diff ./dags'